name: Trivy Scan

on:
  pull_request:
    branches: [ main ]
    paths:
      - "apps/frontend/**"
      - "apps/backend/**"
  push:
    branches: [ main ]
    paths:
      - "apps/frontend/**"
      - "apps/backend/**"
  workflow_dispatch:

jobs:
  trivy-scan-sarif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy FS scan with SARIF
        id: trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          format: sarif
          output: trivy-results.sarif
          scanners: vuln,secret,misconfig
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          scan-ref: |
            apps/frontend
            apps/backend

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif