name: Trivy Code Scan

on:
  workflow_dispatch:
#   push:
#     branches:
#       - main
#     paths:
#       - "apps/frontend/**"
#       - "apps/backend/**"
#   pull_request:
#     branches:
#       - main
#     paths:
#       - "apps/frontend/**"
#       - "apps/backend/**"

jobs:
  trivy-code-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy code scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          scanners: vuln,secret,misconfig
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          format: sarif
          output: trivy-code-results.sarif
          scan-ref: apps/frontend apps/backend
        continue-on-error: true

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-code-results.sarif
